//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Subscription_Master
    {
        public int Gym_ID { get; set; }
        public string Gym_Name { get; set; }
        public int Plan_Amount { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<bool> Active_Flag { get; set; }
        public Nullable<int> Total_Month { get; set; }
        public Nullable<bool> Jan { get; set; }
        public Nullable<bool> Feb { get; set; }
        public Nullable<bool> Mar { get; set; }
        public Nullable<bool> Apr { get; set; }
        public Nullable<bool> May { get; set; }
        public Nullable<bool> Jun { get; set; }
        public Nullable<bool> jul { get; set; }
        public Nullable<bool> Aug { get; set; }
        public Nullable<bool> Sep { get; set; }
        public Nullable<bool> Oct { get; set; }
        public Nullable<bool> Nov { get; set; }
        public Nullable<bool> Dec { get; set; }
    
        public virtual Gym_Master Gym_Master { get; set; }
    }
}
