//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym_Master
    {
        public Gym_Master()
        {
            this.Customer_Subscription_Master = new HashSet<Customer_Subscription_Master>();
        }
    
        public int Gym_ID { get; set; }
        public string Gym_Name { get; set; }
        public string Password { get; set; }
        public string Owner_Name { get; set; }
        public string Address { get; set; }
        public Nullable<long> Contact_No { get; set; }
        public long Adhaar_No { get; set; }
        public string Pan_No { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Role_ID { get; set; }
        public byte[] Gym_Logo { get; set; }
    
        public virtual ICollection<Customer_Subscription_Master> Customer_Subscription_Master { get; set; }
    }
}
