//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Master
    {
        public int Student_ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<int> Advanced_Fees { get; set; }
        public Nullable<int> Monthly_Fees { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<int> Fees_Amount { get; set; }
        public string Address { get; set; }
        public Nullable<long> Adhaar_No { get; set; }
        public string Mobile_No { get; set; }
        public Nullable<bool> Active_Flag { get; set; }
        public string Created_by { get; set; }
        public Nullable<int> Total_Month { get; set; }
        public byte[] Image { get; set; }
    }
}
